### ISSUE TITLE
Wrong file identifier

### ISSUE THREAD

**Issue by thering1975TG** [toddrob99/searcharr#49] opened 2022-04-24 19:08 UTC
Have an odd issue.

Searcharr has been running fine, however i noticed a group chat where there was no response. so i went looking for where the issue is. The whoile setup has not changed at all so not sure where the issue lies.

I have tested several /movie and /tv commands and most are fine.

however 2 examples i have for now "/movie vortex" and "/movie the last detail" both give the following error in the logs

`Caught error: Wrong file identifier/http url specified`

Cant work out why however

**Comment by toddrob99** [comment] 2022-04-24 20:26
I can reproduce the error, but I don't immediately see the cause. I will have to research further.

**Comment by toddrob99** [comment] 2022-04-28 01:08
I tried to capture some logs of the issue for deeper analysis, but I can no longer reproduce the error. Please try again and let me know if you are still seeing the problem.

**Comment by toddrob99** [comment] 2022-04-28 19:57
A user in the Telegram group reported this issue when searching `/movie groundhogs` and `/movie flux gourmet`, which are both currently causing the error for me. I hope to research deeper with these examples.

**Comment by toddrob99** [comment] 2022-04-28 20:19
It looks like Telegram is reporting a different error message than before when it doesn't like a movie/series poster image. I am updating Searcharr to use a default poster image when this new error message is encountered. The fix will be in v2.1.4 probably later today, and it's being built in the beta branch right now.

**Comment by toddrob99** [comment] 2022-04-28 21:01
fixed in v2.1.4

**Closed by toddrob99** 2022-04-28 21:01 UTC
Labels: bug

**Comment by thering1975TG** [comment] 2022-04-30 11:29
Yep fixed, thanks

**Comment by SavageCore** [comment] 2023-05-19 04:25
Happening again:

```
2023-05-19 05:21:37,794 -    DEBUG - searcharr(140093794192184):1405 - Stripped entities from message [/movie Clerks 3]: [Clerks 3]
2023-05-19 05:21:37,794 -    DEBUG - searcharr.radarr(140093794192184):146 - Submitting GET request: [http://localhost:7878/api/v3/movie/lookup?apikey=redacted&term=Clerks%203]
2023-05-19 05:21:38,016 -    DEBUG - searcharr(140093794192184):1691 - Database connection established [/app/data/searcharr.db].
2023-05-19 05:21:38,018 -    DEBUG - searcharr(140093794192184):1691 - Database connection established [/app/data/searcharr.db].
2023-05-19 05:21:38,019 -    DEBUG - searcharr(140093794192184):1442 - Executing query: [INSERT OR REPLACE INTO conversations (id, username, type, results) VALUES (?, ?, ?, ?)] with args: [('ce3d39b9', 'savagecore', 'movie', '[{"title": "The Clerks 3 Documentary", "overview": "Documentary on the making of Clerks 3", "status": "announced", "inCinemas": null, "remotePoster": "https://image.tmdb.org/t/p/original/v1J7hfij55BN5ptwSvCpXRtEBcY.jpg", "year": 2022, "tmdbId": 1058229, "imdbId": "tt23117900", "runtime": 96, "id": null, "titleSlug": "1058229", "images": [{"coverType": "poster", "url": "/radarr/MediaCoverProxy/a6876410c516433a4af04755a751827f4c36945f21bdcb45698db22c28a58987/v1J7hfij55BN5ptwSvCpXRtEBcY.jpg", "remoteUrl": "https://image.tmdb.org/t/p/original/v1J7hfij55BN5ptwSvCpXRtEBcY.jpg"}]}, {"title": "We\'re Not Even Supposed To Be Here Today: 3 Decades of Clerks Documentary", "overview": "A documentary covering 3 decades of Clerks films", "status": "released", "inCinemas": null, "remotePoster": "https://image.tmdb.org/t/p/original/thJxfcv6pCUamVxCAsHloClijmw.jpg", "year": 2022, "tmdbId": 1063682, "imdbId": null, "runtime": 75, "id": null, "titleSlug": "1063682", "images": [{"coverType": "poster", "url": "/radarr/MediaCoverProxy/42c9073a12742c752bf132ce723844147d5ac9ac5260de8f43f2aaa5a3c550f7/thJxfcv6pCUamVxCAsHloClijmw.jpg", "remoteUrl": "https://image.tmdb.org/t/p/original/thJxfcv6pCUamVxCAsHloClijmw.jpg"}]}, {"title": "Clerks III", "overview": "After narrowly surviving a massive heart attack, Randal enlists his old friend Dante to help him make a movie immortalizing their youthful days at the little convenience store that started it all.", "status": "released", "inCinemas": "2022-09-16T00:00:00Z", "remotePoster": "https://image.tmdb.org/t/p/original/apzIqZIQLc8fNx5nbbcSSfPFtax.jpg", "year": 2022, "tmdbId": 635891, "imdbId": "tt11128440", "runtime": 100, "id": 74, "titleSlug": "635891", "images": [{"coverType": "poster", "url": "/radarr/MediaCover/74/poster.jpg?lastWrite=638092677181546378", "remoteUrl": "https://image.tmdb.org/t/p/original/apzIqZIQLc8fNx5nbbcSSfPFtax.jpg"}, {"coverType": "fanart", "url": "/radarr/MediaCover/74/fanart.jpg?lastWrite=638039944807429529", "remoteUrl": "https://image.tmdb.org/t/p/original/5tqWi8wEV88meo6OAC6N1hTdNrj.jpg"}]}]')]
2023-05-19 05:21:38,071 -    ERROR - searcharr(140093794192184):1339 - Caught error: Wrong file identifier/http url specified
```

**Comment by toddrob99** [comment] 2023-06-08 15:21
> Happening again:
> 
> ```
> 2023-05-19 05:21:37,794 -    DEBUG - searcharr(140093794192184):1405 - Stripped entities from message [/movie Clerks 3]: [Clerks 3]
> 2023-05-19 05:21:37,794 -    DEBUG - searcharr.radarr(140093794192184):146 - Submitting GET request: [http://localhost:7878/api/v3/movie/lookup?apikey=redacted&term=Clerks%203]
> 2023-05-19 05:21:38,016 -    DEBUG - searcharr(140093794192184):1691 - Database connection established [/app/data/searcharr.db].
> 2023-05-19 05:21:38,018 -    DEBUG - searcharr(140093794192184):1691 - Database connection established [/app/data/searcharr.db].
> 2023-05-19 05:21:38,019 -    DEBUG - searcharr(140093794192184):1442 - Executing query: [INSERT OR REPLACE INTO conversations (id, username, type, results) VALUES (?, ?, ?, ?)] with args: [('ce3d39b9', 'savagecore', 'movie', '[{"title": "The Clerks 3 Documentary", "overview": "Documentary on the making of Clerks 3", "status": "announced", "inCinemas": null, "remotePoster": "https://image.tmdb.org/t/p/original/v1J7hfij55BN5ptwSvCpXRtEBcY.jpg", "year": 2022, "tmdbId": 1058229, "imdbId": "tt23117900", "runtime": 96, "id": null, "titleSlug": "1058229", "images": [{"coverType": "poster", "url": "/radarr/MediaCoverProxy/a6876410c516433a4af04755a751827f4c36945f21bdcb45698db22c28a58987/v1J7hfij55BN5ptwSvCpXRtEBcY.jpg", "remoteUrl": "https://image.tmdb.org/t/p/original/v1J7hfij55BN5ptwSvCpXRtEBcY.jpg"}]}, {"title": "We\'re Not Even Supposed To Be Here Today: 3 Decades of Clerks Documentary", "overview": "A documentary covering 3 decades of Clerks films", "status": "released", "inCinemas": null, "remotePoster": "https://image.tmdb.org/t/p/original/thJxfcv6pCUamVxCAsHloClijmw.jpg", "year": 2022, "tmdbId": 1063682, "imdbId": null, "runtime": 75, "id": null, "titleSlug": "1063682", "images": [{"coverType": "poster", "url": "/radarr/MediaCoverProxy/42c9073a12742c752bf132ce723844147d5ac9ac5260de8f43f2aaa5a3c550f7/thJxfcv6pCUamVxCAsHloClijmw.jpg", "remoteUrl": "https://image.tmdb.org/t/p/original/thJxfcv6pCUamVxCAsHloClijmw.jpg"}]}, {"title": "Clerks III", "overview": "After narrowly surviving a massive heart attack, Randal enlists his old friend Dante to help him make a movie immortalizing their youthful days at the little convenience store that started it all.", "status": "released", "inCinemas": "2022-09-16T00:00:00Z", "remotePoster": "https://image.tmdb.org/t/p/original/apzIqZIQLc8fNx5nbbcSSfPFtax.jpg", "year": 2022, "tmdbId": 635891, "imdbId": "tt11128440", "runtime": 100, "id": 74, "titleSlug": "635891", "images": [{"coverType": "poster", "url": "/radarr/MediaCover/74/poster.jpg?lastWrite=638092677181546378", "remoteUrl": "https://image.tmdb.org/t/p/original/apzIqZIQLc8fNx5nbbcSSfPFtax.jpg"}, {"coverType": "fanart", "url": "/radarr/MediaCover/74/fanart.jpg?lastWrite=638039944807429529", "remoteUrl": "https://image.tmdb.org/t/p/original/5tqWi8wEV88meo6OAC6N1hTdNrj.jpg"}]}]')]
> 2023-05-19 05:21:38,071 -    ERROR - searcharr(140093794192184):1339 - Caught error: Wrong file identifier/http url specified
> ```

The error message in your log is exactly the one that I added. Also, I am able to search for the same movie and get the result without issue. Please ensure you are running Searcharr v2.1.4+ @SavageCore
